Add Tag, $ref starting to reference schema IDs
Sage-Bionetworks/rocc-schemas pull request #27
Opened 2020-12-10 20:05 UTC by tschaffter

2020-12-10 21:01 UTC, vpchung approved these changes
looks good to me!

2020-12-10 21:02 UTC, vpchung commented
I think some changes will be needed for the Person schema as well; `organizations` is currently not one of its properties. I can make the changes.

2020-12-11 05:39 UTC, vpchung requested changes
Just some minor changes to Person then I think we're good to go!

2020-12-11 05:39 UTC, vpchung commented on openapi/components/schemas/Person.yaml
>  required:
We should probably add `organizations` as a property.

The User schema originally had it, but I think it might be more appropriate here.

2020-12-11 05:39 UTC, vpchung commented on openapi/components/schemas/Person.yaml
>    - email
I think for now, we should remove `email` from "required" (since I don't readily have that information available in the landscape right now).

I originally listed it so that we can ensure the relationship between `User` and `Person`, but for the time being, we probably don't need this assurance.

2020-12-11 05:39 UTC, vpchung commented on openapi/components/schemas/OrganizationId.yaml
> +example: awesome-organization
Oooo, IDs will be arbitrary strings? I'm used to iterative IDs, like `org0001`, `org0002`, etc. This will be interesting!

2020-12-13 01:38 UTC, tschaffter commented on openapi/components/schemas/Person.yaml
>    - email
Added in d40e5eda135bffe79836a250ab97354a4d58e0f1

2020-12-13 01:39 UTC, tschaffter commented on openapi/components/schemas/Person.yaml
>  required:
Added in d40e5eda135bffe79836a250ab97354a4d58e0f1

2020-12-13 01:40 UTC, tschaffter commented on openapi/components/schemas/Person.yaml
>    - email
Addressed in 4baa550da59fa4ffa3c081554d33f11a3ab94d15

2020-12-13 01:52 UTC, tschaffter commented on openapi/components/schemas/OrganizationId.yaml
> +example: awesome-organization
Using incremental IDs is often not encouraged because it leaks information about the total number of items in a collection. IDs that includes some randomness are often the best option as they are more secure because they often don't allow to tie items by their ID, while two consecutive, incremental IDs have a higher chance to be related and an attacker could use this information (e.g. on Synapse often the production and staging site of a DREAM challenge have consecutive IDs).

2020-12-15 07:06 UTC, vpchung approved these changes
Looks good

2020-12-15 07:10 UTC, merged