Add User schema and paths
Sage-Bionetworks/rocc-schemas pull request #61
Opened 2021-01-22 08:21 UTC by vpchung

With this PR:

- adding `User` schema and other related schemas (#47)
- adding paths and operations for `User`
- updating `openapi/openapi.yaml` to include the changes

For this schema, I am using [Google Workspace user API](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users) as reference.  I think it has some properties that we could potentially utilize in the future.

2021-01-22 08:22 UTC, vpchung commented
Not fully fleshed out, so converting to draft.

2021-02-01 18:33 UTC, vpchung commented
@tschaffter not ready yet, sorry!

There's one thing I need to fix for the User* schemas, regarding `password`.

2021-02-02 00:33 UTC, tschaffter requested changes
Looks good! I have a few comments and requests.

2021-02-02 00:33 UTC, tschaffter commented on openapi/components/schemas/PageOfUsers.yaml
> +          $ref: UserGetResponse.yaml
This is less than ideal. Let's target to return a `User` object (does not include properties like `password` and `salt`). Out of curiosity, have you seen `UserGetResponse` used in another project (Google?).

2021-02-02 00:33 UTC, tschaffter commented on openapi/components/schemas/UserGetResponse.yaml
> +description: A user of the portal
Replace by "A user of the service"? One can make a query without using the portal.

2021-02-02 00:33 UTC, tschaffter commented on openapi/openapi.yaml
>  servers:
Tom told me that he had issues working on a client generated from an `openapi.json` that has the property `servers` generated as we do it here (I forgot the specifics). In the NLP Sandbox Data Node I went back to

```
servers:
  - http://...
  - https://..
```

Let's keep this format here unless you meet an issue when working with the Python client.

2021-02-02 02:30 UTC, vpchung commented on openapi/components/schemas/PageOfUsers.yaml
> +          $ref: UserGetResponse.yaml
I have not. I created `UserGetResponse` solely for the purpose of returning a payload that included all the `User` properties except for `password`.

I'll go ahead and remove the `password` property for now, until I look further into authorization/authentication!

2021-02-02 02:30 UTC, vpchung commented on openapi/components/schemas/UserGetResponse.yaml
> +description: A user of the portal
Makes sense!

2021-02-02 02:35 UTC, vpchung commented on openapi/openapi.yaml
>  servers:
Good to know!

To be honest, this was something I was trying out as I was reading through the OpenAPI docs and forgot to change back.  I'm not sure if it actually serves any benefit over the approach used in NLP Sandbox.

2021-02-02 02:46 UTC, vpchung commented on openapi/openapi.yaml
>  servers:
Good to know!

To be honest, this was something I was trying out as I was reading through the OpenAPI docs and forgot to change back. I'm not sure if it actually serves any benefit over the approach used in NLP Sandbox.

2021-02-02 07:05 UTC, tschaffter commented
Looks great!

2021-02-02 07:06 UTC, merged