Update ids
Sage-Bionetworks/rocc-schemas pull request #86
Opened 2021-03-30 19:15 UTC by vpchung

With this PR:

- `Challenge.id` is now of type, string, instead of ObjectId, and must follow Github's naming format (similar to Tag IDs and Organization IDs) (#85)
- `[schema].*Id` renamed to `[schema].id`
- ~paths updated to utilize `id` instead of `*Id`~

2021-03-30 19:53 UTC, tschaffter requested changes

2021-03-30 19:53 UTC, tschaffter commented on openapi/openapi.yaml
> +  /challenges/{id}:
Is this what Google API does? Consider the fictional endpoint below:

`/api/v1/organizations/{organizationId}/challenges/{challengeId}`

He we would need a way to distinguish the two path parameters. To be more consistent, I would always use the path/query parameter `challengeId` in order to be more descriptive and consistent. We could use `challengeId` only when there is more than one "id" needed but that means that sometimes the path/query parameter for challenge id is referenced by "id" and sometimes by "challengeId", which is consistent.

2021-03-30 20:45 UTC, vpchung commented on openapi/openapi.yaml
> +  /challenges/{id}:
Hmm, that is true.  In that case, I prefer how GitHub approaches their paths better.  That is, they save `*_id` fo parameters that are integers and they use arbitrary names for strings.  For example, their path for [checking a team's permission](https://docs.github.com/en/rest/reference/teams#check-team-permissions-for-a-project) is:

`/orgs/{org}/teams/{team_slug}/projects/{project_id}`

where `org` and `team_slug` are strings and `project_id` is an integer.

What do you think?

P.S. GH also uses [OpenAPI](https://github.com/github/rest-api-description) 😉

2021-03-30 21:08 UTC, tschaffter commented on openapi/openapi.yaml
> +  /challenges/{id}:
We use camel case in our schemas. So that would be `challengeId`, `projectId`, etc.

2021-03-30 21:13 UTC, vpchung commented on openapi/openapi.yaml
> +  /challenges/{id}:
Yep, I know that.  But what I'm proposing that the path be:

`/api/v1/organizations/{organization}/challenges/{challenge}`

Since their IDs are strings.

2021-03-30 21:15 UTC, tschaffter commented on openapi/openapi.yaml
> +  /challenges/{id}:
Why would the type of the ID matter regarding the naming of path parameters?

2021-03-31 01:33 UTC, vpchung commented on openapi/openapi.yaml
> +  /challenges/{id}:
Ah, because that's how GH approaches the parameter naming with their paths. That is, the parameters that are integers follow the `*_id` convention, whereas the parameters that are strings will be some name without `id`.  So like in the example above, their path for checking team permissions is:

`/orgs/{org}/teams/{team_slug}/projects/{project_id}`

where `org` and `team_slug` are strings and `project_id` is an integer.

In our case, `Challenge.id` and `Organization.id` are strings, so I'm proposing that the fictional path be something like:

`/api/v1/organizations/{organization}/challenges/{challenge}`

rather than

`/api/v1/organizations/{organizationId}/challenges/{challengeId}`

For `[schema].id`s that are of type ObjectId, we could continue using the naming convention of `*Id` for the path param, e.g.

`/api/v1/persons/{personId}`

If that's too convoluted, I can return the path names to their previous names.

2021-03-31 04:48 UTC, tschaffter commented on openapi/openapi.yaml
> +  /challenges/{id}:
> If that's too convoluted, I can return the path names to their previous names.

I think that it's too convoluted. I haven't see that in any other APIs. I suggest that we stick to `organizationId` for path and query params.

2021-03-31 05:16 UTC, vpchung commented on openapi/openapi.yaml
> +  /challenges/{id}:
Okay dokes.

2021-03-31 15:50 UTC, tschaffter requested changes

2021-03-31 17:07 UTC, vpchung commented on openapi/paths/tags@{tagId}.yaml
> +    "200":
Whoops, thanks for the catch.  I need to reconfigure my VSCode settings.

2021-03-31 17:18 UTC, tschaffter approved these changes

2021-03-31 17:18 UTC, merged